### ISSUE TITLE
Issue with handleErrorFromBinding(ctx) in Windows

### ISSUE THREAD

**Issue by zaaakher** [remorses/tsc-shame#3] opened 2024-07-18 05:10 UTC
I ran `npx tsc-shame@latest` and got the following error:

![image](https://github.com/user-attachments/assets/94c99e49-0d4c-40bd-8504-1948b68b0794)

OS: Windows 10
Node: v18.20.3
PNPM: 9.5.0

**Comment by remorses** [comment] 2024-07-18 11:34
should be fixed now, the problem is the space in the path

**Closed as completed by remorses** 2024-07-18 11:34 UTC
